DELETE FROM check_points WHERE category IN ('소화전', '비상콘센트');
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-8F-1-BC', '비상콘센트', '8F-1', '북측 공조실 안', '8F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-8F-2-SH', '소화전', '8F-2', '실험동물센터 앞', '8F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-8F-3-SH', '소화전', '8F-3', '계단실 4 앞', '8F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-8F-4-SH', '소화전', '8F-4', '동측 공조실 안', '8F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-8F-5-SH', '소화전', '8F-5', '투명 E/V 앞', '8F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-8F-6-SH', '소화전', '8F-6', '게스트하우스 복도 끝', '8F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-8F-7-BC', '비상콘센트', '8F-7', '계단실 2 옆', '8F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-8F-8-SH', '소화전', '8F-8', '남자 화장실 앞', '8F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-7F-1-BC', '비상콘센트', '7F-1', '북측 공조실 앞', '7F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-7F-2-SH', '소화전', '7F-2', '706 연구실 입구', '7F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-7F-3-BC', '비상콘센트', '7F-3', '화물 E/V 앞', '7F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-7F-4-SH', '소화전', '7F-4', '721 연구실 입구', '7F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-7F-5-SH', '소화전', '7F-5', '동측 공조실 앞', '7F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-7F-6-SH', '소화전', '7F-6', '남측 사무실 탕비실 안', '7F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-7F-7-SH', '소화전', '7F-7', '계단실 1 앞', '7F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-7F-8-BC', '비상콘센트', '7F-8', '계단실 2 옆', '7F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-7F-9-SH', '소화전', '7F-9', '남측 사무실 안', '7F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-6F-1-SH', '소화전', '6F-1', '북측 공조실 앞', '6F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-6F-2-SH', '소화전', '6F-2', '606 연구실 입구', '6F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-6F-3-SH', '소화전', '6F-3', '화물 E/V 앞', '6F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-6F-4-SH', '소화전', '6F-4', '622 연구실 입구', '6F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-6F-5-SH', '소화전', '6F-5', '동측 공조실 앞', '6F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-6F-6-SH', '소화전', '6F-6', '남측 사무실 탕비실 안', '6F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-6F-7-SH', '소화전', '6F-7', '계단실 1 앞', '6F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-6F-8-SH', '소화전', '6F-8', '계단실 2 옆', '6F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-6F-9-SH', '소화전', '6F-9', '남측 사무실 안', '6F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-5F-1-SH', '소화전', '5F-1', '북측 공조실 앞', '5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-5F-2-SH', '소화전', '5F-2', '506 연구실 입구', '5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-5F-3-SH', '소화전', '5F-3', '화물 E/V 앞', '5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-5F-4-SH', '소화전', '5F-4', '522 연구실 입구', '5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-5F-5-SH', '소화전', '5F-5', '동측 공조실 앞', '5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-5F-6-SH', '소화전', '5F-6', '회의실 안', '5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-5F-7-SH', '소화전', '5F-7', '계단실 1 앞', '5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-5F-8-SH', '소화전', '5F-8', '계단실 2 옆', '5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-5F-9-SH', '소화전', '5F-9', '비서실 안', '5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-3F-1-SH', '소화전', '3F-1', '북측 공조실 앞', '3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-3F-2-SH', '소화전', '3F-2', '307 연구실 입구', '3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-3F-3-SH', '소화전', '3F-3', '화물 E/V 앞', '3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-3F-4-SH', '소화전', '3F-4', '323 연구실 입구', '3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-3F-5-SH', '소화전', '3F-5', '동측 공조실 앞', '3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-3F-6-SH', '소화전', '3F-6', '3층 로비 탕비실 안', '3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-3F-7-SH', '소화전', '3F-7', '계단실 1 앞', '3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-3F-8-SH', '소화전', '3F-8', '계단실 2 옆', '3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-3F-9-SH', '소화전', '3F-9', '33회의실 옆', '3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-2F-1-SH', '소화전', '2F-1', '미디어홀 앞', '2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-2F-2-SH', '소화전', '2F-2', '안내데스크 옆', '2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-2F-3-SH', '소화전', '2F-3', '계단실 4 옆', '2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-2F-4-SH', '소화전', '2F-4', '홍보관 옆', '2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-2F-5-SH', '소화전', '2F-5', '동측 복도 끝', '2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-2F-6-SH', '소화전', '2F-6', '계단실 1 앞', '2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-2F-7-SH', '소화전', '2F-7', '계단실 2 옆', '2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-2F-8-SH', '소화전', '2F-8', '남측 사무실 안', '2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-1F-1-SH', '소화전', '1F-1', '북측 공조실 안', '1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-1F-2-SH', '소화전', '1F-2', '제대혈 사무실 앞', '1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-1F-3-SH', '소화전', '1F-3', '계단실 4 옆', '1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-1F-4-SH', '소화전', '1F-4', 'GMP 복도', '1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-1F-5-SH', '소화전', '1F-5', 'GMP 복도 끝', '1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-1F-6-SH', '소화전', '1F-6', '계단실 1 옆', '1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-1F-7-SH', '소화전', '1F-7', '계단실 2 옆', '1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-1F-8-SH', '소화전', '1F-8', '남측 사무실 안', '1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-1F-9-SH', '소화전', '1F-9', '창고 옆', '1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-1F-10-SH', '소화전', '1F-10', '제대혈 탱크실 안', '1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B1F-1-BC', '비상콘센트', 'B1F-1', '방재실 옆', 'B1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B1F-2-BC', '비상콘센트', 'B1F-2', '식당 퇴식구 옆', 'B1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B1F-3-BC', '비상콘센트', 'B1F-3', '국제회의실 앞', 'B1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B1F-4-BC', '비상콘센트', 'B1F-4', '계단실 4 앞', 'B1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B1F-5-BC', '비상콘센트', 'B1F-5', '대강당 옆', 'B1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B1F-6-BC', '비상콘센트', 'B1F-6', '재단 시설팀 안', 'B1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B1F-7-BC', '비상콘센트', 'B1F-7', 'E/V #7 앞', 'B1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B1F-8-BC', '비상콘센트', 'B1F-8', '계단실 2 옆', 'B1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B1F-9-BC', '비상콘센트', 'B1F-9', '대학사무실 옆', 'B1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B1F-10-BC', '비상콘센트', 'B1F-10', '식당 영양사실 옆', 'B1F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B2F-1-BC', '비상콘센트', 'B2F-1', '계단실 5 옆', 'B2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B2F-2-BC', '비상콘센트', 'B2F-2', '난임트레이닝센터 실습실 옆', 'B2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B2F-3-BC', '비상콘센트', 'B2F-3', '계단실 4 옆', 'B2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B2F-4-BC', '비상콘센트', 'B2F-4', 'B230 강의실 옆', 'B2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B2F-5-BC', '비상콘센트', 'B2F-5', '계단실 3 옆', 'B2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B2F-6-BC', '비상콘센트', 'B2F-6', '남문 측 계단 앞', 'B2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B2F-7-BC', '비상콘센트', 'B2F-7', '계단실 2 옆', 'B2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B2F-8-BC', '비상콘센트', 'B2F-8', 'B201 강의실 옆', 'B2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B2F-9-BC', '비상콘센트', 'B2F-9', '북측 공조실 앞', 'B2F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B3F-1-BC', '비상콘센트', 'B3F-1', '폐수처리조 안', 'B3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B3F-2-BC', '비상콘센트', 'B3F-2', '폐수처리조 밖', 'B3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B3F-3-BC', '비상콘센트', 'B3F-3', '계단실 5 안', 'B3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B3F-4-BC', '비상콘센트', 'B3F-4', '계단실 2 옆', 'B3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B3F-5-BC', '비상콘센트', 'B3F-5', '미화사무실 앞 기둥', 'B3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B3F-6-BC', '비상콘센트', 'B3F-6', '팬룸 1 옆', 'B3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B3F-7-BC', '비상콘센트', 'B3F-7', 'D - 7 기둥', 'B3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B3F-8-BC', '비상콘센트', 'B3F-8', '투명 E/V 앞', 'B3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B3F-9-BC', '비상콘센트', 'B3F-9', '계단실 4 옆', 'B3F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B4F-1-BC', '비상콘센트', 'B4F-1', 'I - 1 기둥 옆', 'B4F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B4F-2-BC', '비상콘센트', 'B4F-2', '계단실 5 안', 'B4F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B4F-3-BC', '비상콘센트', 'B4F-3', '기계실 안', 'B4F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B4F-4-BC', '비상콘센트', 'B4F-4', '계단실 2 옆', 'B4F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B4F-5-BC', '비상콘센트', 'B4F-5', 'B - 2 기둥 앞', 'B4F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B4F-6-BC', '비상콘센트', 'B4F-6', '팬룸 1 옆', 'B4F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B4F-7-BC', '비상콘센트', 'B4F-7', 'D - 7 기둥', 'B4F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B4F-8-BC', '비상콘센트', 'B4F-8', '투명 E/V 앞', 'B4F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B4F-9-BC', '비상콘센트', 'B4F-9', '계단실 4 옆', 'B4F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B5F-1-BC', '비상콘센트', 'B5F-1', '쓰레기장 옆', 'B5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B5F-2-BC', '비상콘센트', 'B5F-2', '투명 E/V 앞', 'B5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B5F-3-BC', '비상콘센트', 'B5F-3', '계단실 2 옆', 'B5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B5F-4-BC', '비상콘센트', 'B5F-4', '램프 옆', 'B5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B5F-5-BC', '비상콘센트', 'B5F-5', '팬룸 1 옆', 'B5F', 1, datetime('now'));
INSERT INTO check_points (id, category, location_no, location, floor, is_active, created_at) VALUES ('CP-B5F-6-BC', '비상콘센트', 'B5F-6', '계단실 4 옆', 'B5F', 1, datetime('now'));
